codecov:
  notify:
    require_ci_to_pass: no

coverage:
  status:
    project:
      default:
        # basic
        target: 0
        threshold: null
    patch:
      default:
        target: 0
        threshold: null
