dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly" # currently points to 3.8-dev

matrix:
  include:
    - python: 3.7
      env:
        - COVERAGE=1

# Setup anaconda
before_install:
  - python -m pip install --upgrade pip
  - pip install "pytest>=3.4" pytest-cov codecov
  - pip install -r requirements.txt

install:
  - python setup.py install

script:
  - |
    if [ "${COVERAGE}" == "1" ]; then
        TEST_ARGS="--cov-report term-missing --cov=rapidtide";
    else
        TEST_ARGS="";
    fi
    pytest ${TEST_ARGS} rapidtide;

after_success:
  - codecov
